[[tests]]
name = "add4-1"
input = ["./target/debug/add4", "1", "2", "3", "4"]
expected = """
Rust: 10
Asm: 10
"""
rubric = 10

[[tests]]
name = "add4-2"
input = ["./target/debug/add4", "-1", "2", "3", "4"]
expected = """
Rust: 8
Asm: 8
"""
rubric = 10

[[tests]]
name = "quadratic-1"
input = ["./target/debug/quadratic", "4", "3", "2", "1"]
expected = """
Rust: 57
Asm: 57
"""
rubric = 10

[[tests]]
name = "quadratic-2"
input = ["./target/debug/quadratic", "2", "4", "6", "8"]
expected = """
Rust: 36
Asm: 36
"""
rubric = 10

[[tests]]
name = "min-1"
input = ["./target/debug/min", "1", "2"]
expected = """
Rust: 1
Asm: 1
"""
rubric = 15

[[tests]]
name = "min-2"
input = ["./target/debug/min", "2", "-1"]
expected = """
Rust: -1
Asm: -1
"""
rubric = 15

[[tests]]
name = "findmax-1"
input = ["./target/debug/findmax", "1", "2", "33", "4", "5"]
expected = """
Rust: 33
Asm: 33
"""
rubric = 15

[[tests]]
name = "findmax-2"
input = ["./target/debug/findmax", "1", "2", "3", "4", "5", "6", "99"]
expected = """
Rust: 99
Asm: 99
"""
rubric = 15

[[tests]]
name = "grade-1"
input = ["./target/debug/grade", "85"]
expected = """
Rust: 3
Asm: 3
"""
rubric = 10

[[tests]]
name = "grade-2"
input = ["./target/debug/grade", "55"]
expected = """
Rust: 0
Asm: 0
"""
rubric = 10

[[tests]]
name = "sum_to_n-1"
input = ["./target/debug/sum_to_n", "10"]
expected = """
Rust: 55
Asm: 55
"""
rubric = 10

[[tests]]
name = "sum_to_n-2"
input = ["./target/debug/sum_to_n", "1"]
expected = """
Rust: 1
Asm: 1
"""
rubric = 10
