[[tests]]
name = "c-01"
input = ["./c/project01", "-e", "1 + 2"]
expected = """
3
"""
rubric = 1

[[tests]]
name = "c-02"
input = ["./c/project01", "-e", "10", "-b", "16"]
expected = """
0x0000000A
"""
rubric = 1

[[tests]]
name = "c-03"
input = ["./c/project01", "-e", "10 + 1"]
expected = """
11
"""
rubric = 1

[[tests]]
name = "c-04"
input = ["./c/project01", "-e", "10 + 1", "-b", "16"]
expected = """
0x0000000B
"""
rubric = 1

[[tests]]
name = "c-05"
input = ["./c/project01", "-e", "10", "-b", "16", "-w", "16"]
expected = """
0x000A
"""
rubric = 2

[[tests]]
name = "c-06"
input = ["./c/project01", "-e", "10", "-b", "2"]
expected = """
0b00000000000000000000000000001010
"""
rubric = 2

[[tests]]
name = "c-07"
input = ["./c/project01", "-e", "10", "-b", "2", "-w", "4"]
expected = """
0b1010
"""
rubric = 2

[[tests]]
name = "c-08"
input = ["./c/project01", "-e", "0x0A", "-b", "10"]
expected = """
10
"""
rubric = 2

[[tests]]
name = "c-09"
input = ["./c/project01", "-e", "0x0A", "-b", "2", "-w", "8"]
expected = """
0b00001010
"""
rubric = 2

[[tests]]
name = "c-10"
input = ["./c/project01", "-e", "((1 + 1) * 1)", "-b", "16", "-w", "16"]
expected = """
0x0002
"""
rubric = 2

[[tests]]
name = "c-11"
input = ["./c/project01", "-e", "((1 + 1) * 1)", "-b", "2", "-w", "8"]
expected = """
0b00000010
"""
rubric = 2

[[tests]]
name = "c-12"
input = ["./c/project01", "-e", "(1 << 16)", "-b", "10", "-w", "32"]
expected = """
65536
"""
rubric = 2

[[tests]]
name = "c-13"
input = ["./c/project01", "-e", "(1 << 16)", "-b", "10", "-w", "16"]
expected = """
0
"""
rubric = 2

[[tests]]
name = "c-14"
input = ["./c/project01", "-e", "(1 << 16)", "-b", "16", "-w", "32"]
expected = """
0x00010000
"""
rubric = 2

[[tests]]
name = "c-15"
input = ["./c/project01", "-b", "10", "-w", "8", "-e", "(2 * (0b1111 & 0b1010))"]
expected = """
20
"""
rubric = 2

[[tests]]
name = "c-16"
input = ["./c/project01", "-b", "10", "-w", "8", "-e", "0b00001000"]
expected = """
8
"""
rubric = 2

[[tests]]
name = "c-17"
input = ["./c/project01", "-b", "10", "-w", "4", "-e", "0b00001000"]
expected = """
-8
"""
rubric = 2

[[tests]]
name = "c-18"
input = ["./c/project01", "-b", "10", "-u", "-w", "4", "-e", "0b00001000"]
expected = """
8
"""
rubric = 2

[[tests]]
name = "c-19"
input = ["./c/project01", "-b", "10", "-w", "8", "-e", "-128 >- 2"]
expected = """
-32
"""
rubric = 2

[[tests]]
name = "c-20"
input = ["./c/project01", "-e", "(((((~((-(2 * ((1023 + 1) / 4)) >- 2) << 8)) >> 10) ^ 0b01110) & 0x1E) | ~(0b10000))"]
expected = """
-1
"""
rubric = 2

[[tests]]
name = "c-21"
input = ["./c/project01", "-e", "0xffffffff"]
expected = """
-1
"""
rubric = 2


[[tests]]
name = "c-22"
input = ["./c/project01", "-e", "0xffffffff1"]
expected = """
overflows uint32_t: ffffffff1
"""
rubric = 2

[[tests]]
name = "c-23"
input = ["./c/project01", "-e", "0x000000000ffffffff"]
expected = """
-1
"""
rubric = 2

[[tests]]
name = "c-24"
input = ["./c/project01", "$project_tests/p1.ntl"]
expected = """
3
0b00000000000000000000000000000011
0x00000003
0b0011
0x3
"""
rubric = 2

[[tests]]
name = "c-25"
input = ["./c/project01", "$project_tests/p2.ntl"]
expected = """
180
"""
rubric = 2

[[tests]]
name = "c-26"
input = ["./c/project01", "$project_tests/p3.ntl"]
expected = """
241
0b00000000000000000000000011110001
-241
0b11111111111111111111111100001111
-241
0b11111111111111111111111100001111
"""
rubric = 2

[[tests]]
name = "c-27"
input = ["./c/project01", "$project_tests/p4.ntl"]
expected = """
10
"""
rubric = 2


[[tests]]
name = "rust-01"
input = ["./rust/target/debug/project01", "-e", "1 + 2"]
expected = """
3
"""
rubric = 1

[[tests]]
name = "rust-02"
input = ["./rust/target/debug/project01", "-e", "10", "-b", "16"]
expected = """
0x0000000A
"""
rubric = 1

[[tests]]
name = "rust-03"
input = ["./rust/target/debug/project01", "-e", "10 + 1"]
expected = """
11
"""
rubric = 1

[[tests]]
name = "rust-04"
input = ["./rust/target/debug/project01", "-e", "10 + 1", "-b", "16"]
expected = """
0x0000000B
"""
rubric = 1

[[tests]]
name = "rust-05"
input = ["./rust/target/debug/project01", "-e", "10", "-b", "16", "-w", "16"]
expected = """
0x000A
"""
rubric = 2

[[tests]]
name = "rust-06"
input = ["./rust/target/debug/project01", "-e", "10", "-b", "2"]
expected = """
0b00000000000000000000000000001010
"""
rubric = 2

[[tests]]
name = "rust-07"
input = ["./rust/target/debug/project01", "-e", "10", "-b", "2", "-w", "4"]
expected = """
0b1010
"""
rubric = 2

[[tests]]
name = "rust-08"
input = ["./rust/target/debug/project01", "-e", "0x0A", "-b", "10"]
expected = """
10
"""
rubric = 2

[[tests]]
name = "rust-09"
input = ["./rust/target/debug/project01", "-e", "0x0A", "-b", "2", "-w", "8"]
expected = """
0b00001010
"""
rubric = 2

[[tests]]
name = "rust-10"
input = ["./rust/target/debug/project01", "-e", "((1 + 1) * 1)", "-b", "16", "-w", "16"]
expected = """
0x0002
"""
rubric = 2

[[tests]]
name = "rust-11"
input = ["./rust/target/debug/project01", "-e", "((1 + 1) * 1)", "-b", "2", "-w", "8"]
expected = """
0b00000010
"""
rubric = 2

[[tests]]
name = "rust-12"
input = ["./rust/target/debug/project01", "-e", "(1 << 16)", "-b", "10", "-w", "32"]
expected = """
65536
"""
rubric = 2

[[tests]]
name = "rust-13"
input = ["./rust/target/debug/project01", "-e", "(1 << 16)", "-b", "10", "-w", "16"]
expected = """
0
"""
rubric = 2

[[tests]]
name = "rust-14"
input = ["./rust/target/debug/project01", "-e", "(1 << 16)", "-b", "16", "-w", "32"]
expected = """
0x00010000
"""
rubric = 2

[[tests]]
name = "rust-15"
input = ["./rust/target/debug/project01", "-b", "10", "-w", "8", "-e", "(2 * (0b1111 & 0b1010))"]
expected = """
20
"""
rubric = 2

[[tests]]
name = "rust-16"
input = ["./rust/target/debug/project01", "-b", "10", "-w", "8", "-e", "0b00001000"]
expected = """
8
"""
rubric = 2

[[tests]]
name = "rust-17"
input = ["./rust/target/debug/project01", "-b", "10", "-w", "4", "-e", "0b00001000"]
expected = """
-8
"""
rubric = 2

[[tests]]
name = "rust-18"
input = ["./rust/target/debug/project01", "-b", "10", "-u", "-w", "4", "-e", "0b00001000"]
expected = """
8
"""
rubric = 2

[[tests]]
name = "rust-19"
input = ["./rust/target/debug/project01", "-b", "10", "-w", "8", "-e", "-128 >- 2"]
expected = """
-32
"""
rubric = 2

[[tests]]
name = "rust-20"
input = ["./rust/target/debug/project01", "-e", "(((((~((-(2 * ((1023 + 1) / 4)) >- 2) << 8)) >> 10) ^ 0b01110) & 0x1E) | ~(0b10000))"]
expected = """
-1
"""
rubric = 2

[[tests]]
name = "rust-21"
input = ["./rust/target/debug/project01", "-e", "0xffffffff"]
expected = """
-1
"""
rubric = 2

[[tests]]
name = "rust-22"
input = ["./rust/target/debug/project01", "-e", "0xffffffff1"]
expected = """
overflows uint32_t: ffffffff1
"""
rubric = 2

[[tests]]
name = "rust-23"
input = ["./rust/target/debug/project01", "-e", "0x000000000ffffffff"]
expected = """
-1
"""
rubric = 2

[[tests]]
name = "rust-24"
input = ["./rust/target/debug/project01", "$project_tests/p1.ntl"]
expected = """
3
0b00000000000000000000000000000011
0x00000003
0b0011
0x3
"""
rubric = 2

[[tests]]
name = "rust-25"
input = ["./rust/target/debug/project01", "$project_tests/p2.ntl"]
expected = """
180
"""
rubric = 2

[[tests]]
name = "rust-26"
input = ["./rust/target/debug/project01", "$project_tests/p3.ntl"]
expected = """
241
0b00000000000000000000000011110001
-241
0b11111111111111111111111100001111
-241
0b11111111111111111111111100001111
"""
rubric = 2

[[tests]]
name = "rust-27"
input = ["./rust/target/debug/project01", "$project_tests/p4.ntl"]
expected = """
10
"""
rubric = 2
